"""Publicly fetchable published files (Printful design publishing, 2026-08-26).

Printful's v2 API ingests design files ONLY by fetching a public URL (POST
/v2/files {url}; no multipart, no data-URI). Bob's box has public HTTPS via
the Tailscale Funnel, so this router serves a small publish directory at an
unguessable token path:

    https://<public-host>/files/<publish_token>/<filename>

The token lives at ``<workspace>/skills/printful/publish_token`` (mode 600,
generated by the skill on first use) and is re-read per request, so rotating
it takes effect immediately with no restart. Only image/print file types are
served, filenames are constrained to the flat publish directory, and
directory listings never happen. The publish directory itself is
``<workspace>/published-files``.
"""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import FileResponse, Response

logger = logging.getLogger(__name__)

router = APIRouter()


# HEAD is included so clients (the printful skill's publish check) can
# verify a URL is live without downloading the body.

ALLOWED_SUFFIXES = {".png", ".jpg", ".jpeg", ".pdf"}
PUBLISH_DIR_NAME = "published-files"
TOKEN_FILE_NAME = "publish_token"


def _workspace_dir(request: Request) -> Path:
    return Path(request.app.state.settings.harness.workspace_dir).expanduser()


def _publish_token(request: Request) -> str | None:
    token_file = _workspace_dir(request) / "skills" / "printful" / TOKEN_FILE_NAME
    try:
        token = token_file.read_text().strip()
        return token or None
    except OSError:
        return None


@router.api_route("/files/{token}/{filename}", methods=["GET", "HEAD"])
async def published_file(token: str, filename: str, request: Request) -> Response:
    # Uniform 404 for wrong token / missing file — nothing about the route's
    # existence is disclosed to anonymous scanners.
    expected = _publish_token(request)
    if not expected or token != expected:
        return Response(status_code=404)

    name = Path(filename)
    if name.suffix.lower() not in ALLOWED_SUFFIXES or name.name != filename:
        return Response(status_code=404)

    path = (_workspace_dir(request) / PUBLISH_DIR_NAME / filename).resolve()
    publish_root = (_workspace_dir(request) / PUBLISH_DIR_NAME).resolve()
    if publish_root not in path.parents or not path.is_file():
        return Response(status_code=404)

    return FileResponse(path)
