/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as SessionsSessionKeyRouteImport } from './routes/sessions/$sessionKey'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as SessionsSessionKeyIndexRouteImport } from './routes/sessions/$sessionKey/index'
import { Route as SessionsSessionKeyCallsCallIdRouteImport } from './routes/sessions/$sessionKey/calls/$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionKeyRoute = SessionsSessionKeyRouteImport.update({
  id: '/sessions/$sessionKey',
  path: '/sessions/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionKeyIndexRoute = SessionsSessionKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionKeyRoute,
} as any)
const SessionsSessionKeyCallsCallIdRoute =
  SessionsSessionKeyCallsCallIdRouteImport.update({
    id: '/calls/$callId',
    path: '/calls/$callId',
    getParentRoute: () => SessionsSessionKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRouteWithChildren
  '/contacts/': typeof ContactsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/sessions/$sessionKey/': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts': typeof ContactsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRouteWithChildren
  '/contacts/': typeof ContactsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/sessions/$sessionKey/': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/$contactId'
    | '/sessions/$sessionKey'
    | '/contacts/'
    | '/sessions/'
    | '/workspace/'
    | '/sessions/$sessionKey/'
    | '/sessions/$sessionKey/calls/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/$contactId'
    | '/contacts'
    | '/sessions'
    | '/workspace'
    | '/sessions/$sessionKey'
    | '/sessions/$sessionKey/calls/$callId'
  id:
    | '__root__'
    | '/'
    | '/contacts/$contactId'
    | '/sessions/$sessionKey'
    | '/contacts/'
    | '/sessions/'
    | '/workspace/'
    | '/sessions/$sessionKey/'
    | '/sessions/$sessionKey/calls/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  SessionsSessionKeyRoute: typeof SessionsSessionKeyRouteWithChildren
  ContactsIndexRoute: typeof ContactsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionKey': {
      id: '/sessions/$sessionKey'
      path: '/sessions/$sessionKey'
      fullPath: '/sessions/$sessionKey'
      preLoaderRoute: typeof SessionsSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionKey/': {
      id: '/sessions/$sessionKey/'
      path: '/'
      fullPath: '/sessions/$sessionKey/'
      preLoaderRoute: typeof SessionsSessionKeyIndexRouteImport
      parentRoute: typeof SessionsSessionKeyRoute
    }
    '/sessions/$sessionKey/calls/$callId': {
      id: '/sessions/$sessionKey/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/sessions/$sessionKey/calls/$callId'
      preLoaderRoute: typeof SessionsSessionKeyCallsCallIdRouteImport
      parentRoute: typeof SessionsSessionKeyRoute
    }
  }
}

interface SessionsSessionKeyRouteChildren {
  SessionsSessionKeyIndexRoute: typeof SessionsSessionKeyIndexRoute
  SessionsSessionKeyCallsCallIdRoute: typeof SessionsSessionKeyCallsCallIdRoute
}

const SessionsSessionKeyRouteChildren: SessionsSessionKeyRouteChildren = {
  SessionsSessionKeyIndexRoute: SessionsSessionKeyIndexRoute,
  SessionsSessionKeyCallsCallIdRoute: SessionsSessionKeyCallsCallIdRoute,
}

const SessionsSessionKeyRouteWithChildren =
  SessionsSessionKeyRoute._addFileChildren(SessionsSessionKeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  SessionsSessionKeyRoute: SessionsSessionKeyRouteWithChildren,
  ContactsIndexRoute: ContactsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
