/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as PhoneIndexRouteImport } from './routes/phone/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as SkillsDelegationIdRouteImport } from './routes/skills/$delegationId'
import { Route as SessionsSessionKeyRouteImport } from './routes/sessions/$sessionKey'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as SessionsSessionKeyIndexRouteImport } from './routes/sessions/$sessionKey/index'
import { Route as PhoneCallIdIndexRouteImport } from './routes/phone/$callId/index'
import { Route as MemoryBulletinsBulletinIdRouteImport } from './routes/memory/bulletins/$bulletinId'
import { Route as SessionsSessionKeyCallsCallIdRouteImport } from './routes/sessions/$sessionKey/calls/$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneIndexRoute = PhoneIndexRouteImport.update({
  id: '/phone/',
  path: '/phone/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsDelegationIdRoute = SkillsDelegationIdRouteImport.update({
  id: '/skills/$delegationId',
  path: '/skills/$delegationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionKeyRoute = SessionsSessionKeyRouteImport.update({
  id: '/sessions/$sessionKey',
  path: '/sessions/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionKeyIndexRoute = SessionsSessionKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionKeyRoute,
} as any)
const PhoneCallIdIndexRoute = PhoneCallIdIndexRouteImport.update({
  id: '/phone/$callId/',
  path: '/phone/$callId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryBulletinsBulletinIdRoute =
  MemoryBulletinsBulletinIdRouteImport.update({
    id: '/memory/bulletins/$bulletinId',
    path: '/memory/bulletins/$bulletinId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionKeyCallsCallIdRoute =
  SessionsSessionKeyCallsCallIdRouteImport.update({
    id: '/calls/$callId',
    path: '/calls/$callId',
    getParentRoute: () => SessionsSessionKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRouteWithChildren
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/phone/': typeof PhoneIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/memory/bulletins/$bulletinId': typeof MemoryBulletinsBulletinIdRoute
  '/phone/$callId/': typeof PhoneCallIdIndexRoute
  '/sessions/$sessionKey/': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts': typeof ContactsIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/phone': typeof PhoneIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/memory/bulletins/$bulletinId': typeof MemoryBulletinsBulletinIdRoute
  '/phone/$callId': typeof PhoneCallIdIndexRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/sessions/$sessionKey': typeof SessionsSessionKeyRouteWithChildren
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/phone/': typeof PhoneIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/memory/bulletins/$bulletinId': typeof MemoryBulletinsBulletinIdRoute
  '/phone/$callId/': typeof PhoneCallIdIndexRoute
  '/sessions/$sessionKey/': typeof SessionsSessionKeyIndexRoute
  '/sessions/$sessionKey/calls/$callId': typeof SessionsSessionKeyCallsCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/$contactId'
    | '/sessions/$sessionKey'
    | '/skills/$delegationId'
    | '/contacts/'
    | '/memory/'
    | '/phone/'
    | '/sessions/'
    | '/skills/'
    | '/workspace/'
    | '/memory/bulletins/$bulletinId'
    | '/phone/$callId/'
    | '/sessions/$sessionKey/'
    | '/sessions/$sessionKey/calls/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts/$contactId'
    | '/skills/$delegationId'
    | '/contacts'
    | '/memory'
    | '/phone'
    | '/sessions'
    | '/skills'
    | '/workspace'
    | '/memory/bulletins/$bulletinId'
    | '/phone/$callId'
    | '/sessions/$sessionKey'
    | '/sessions/$sessionKey/calls/$callId'
  id:
    | '__root__'
    | '/'
    | '/contacts/$contactId'
    | '/sessions/$sessionKey'
    | '/skills/$delegationId'
    | '/contacts/'
    | '/memory/'
    | '/phone/'
    | '/sessions/'
    | '/skills/'
    | '/workspace/'
    | '/memory/bulletins/$bulletinId'
    | '/phone/$callId/'
    | '/sessions/$sessionKey/'
    | '/sessions/$sessionKey/calls/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  SessionsSessionKeyRoute: typeof SessionsSessionKeyRouteWithChildren
  SkillsDelegationIdRoute: typeof SkillsDelegationIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  PhoneIndexRoute: typeof PhoneIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  MemoryBulletinsBulletinIdRoute: typeof MemoryBulletinsBulletinIdRoute
  PhoneCallIdIndexRoute: typeof PhoneCallIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/': {
      id: '/phone/'
      path: '/phone'
      fullPath: '/phone/'
      preLoaderRoute: typeof PhoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$delegationId': {
      id: '/skills/$delegationId'
      path: '/skills/$delegationId'
      fullPath: '/skills/$delegationId'
      preLoaderRoute: typeof SkillsDelegationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionKey': {
      id: '/sessions/$sessionKey'
      path: '/sessions/$sessionKey'
      fullPath: '/sessions/$sessionKey'
      preLoaderRoute: typeof SessionsSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionKey/': {
      id: '/sessions/$sessionKey/'
      path: '/'
      fullPath: '/sessions/$sessionKey/'
      preLoaderRoute: typeof SessionsSessionKeyIndexRouteImport
      parentRoute: typeof SessionsSessionKeyRoute
    }
    '/phone/$callId/': {
      id: '/phone/$callId/'
      path: '/phone/$callId'
      fullPath: '/phone/$callId/'
      preLoaderRoute: typeof PhoneCallIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/bulletins/$bulletinId': {
      id: '/memory/bulletins/$bulletinId'
      path: '/memory/bulletins/$bulletinId'
      fullPath: '/memory/bulletins/$bulletinId'
      preLoaderRoute: typeof MemoryBulletinsBulletinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionKey/calls/$callId': {
      id: '/sessions/$sessionKey/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/sessions/$sessionKey/calls/$callId'
      preLoaderRoute: typeof SessionsSessionKeyCallsCallIdRouteImport
      parentRoute: typeof SessionsSessionKeyRoute
    }
  }
}

interface SessionsSessionKeyRouteChildren {
  SessionsSessionKeyIndexRoute: typeof SessionsSessionKeyIndexRoute
  SessionsSessionKeyCallsCallIdRoute: typeof SessionsSessionKeyCallsCallIdRoute
}

const SessionsSessionKeyRouteChildren: SessionsSessionKeyRouteChildren = {
  SessionsSessionKeyIndexRoute: SessionsSessionKeyIndexRoute,
  SessionsSessionKeyCallsCallIdRoute: SessionsSessionKeyCallsCallIdRoute,
}

const SessionsSessionKeyRouteWithChildren =
  SessionsSessionKeyRoute._addFileChildren(SessionsSessionKeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  SessionsSessionKeyRoute: SessionsSessionKeyRouteWithChildren,
  SkillsDelegationIdRoute: SkillsDelegationIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  PhoneIndexRoute: PhoneIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  MemoryBulletinsBulletinIdRoute: MemoryBulletinsBulletinIdRoute,
  PhoneCallIdIndexRoute: PhoneCallIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
