/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as ConversationsSessionKeyRouteImport } from './routes/conversations/$sessionKey'
import { Route as DreamsIndexRouteImport } from './routes/dreams/index'
import { Route as MemoryIndexRouteImport } from './routes/memory/index'
import { Route as PersonaIndexRouteImport } from './routes/persona/index'
import { Route as PhoneIndexRouteImport } from './routes/phone/index'
import { Route as SessionsSplatRouteImport } from './routes/sessions.$'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsDelegationIdRouteImport } from './routes/skills/$delegationId'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as ConversationsSessionKeyIndexRouteImport } from './routes/conversations/$sessionKey/index'
import { Route as PhoneCallIdIndexRouteImport } from './routes/phone/$callId/index'
import { Route as ConversationsSessionKeyCallsCallIdRouteImport } from './routes/conversations/$sessionKey/calls/$callId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsSessionKeyRoute = ConversationsSessionKeyRouteImport.update({
  id: '/conversations/$sessionKey',
  path: '/conversations/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamsIndexRoute = DreamsIndexRouteImport.update({
  id: '/dreams/',
  path: '/dreams/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIndexRoute = PersonaIndexRouteImport.update({
  id: '/persona/',
  path: '/persona/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneIndexRoute = PhoneIndexRouteImport.update({
  id: '/phone/',
  path: '/phone/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSplatRoute = SessionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SessionsRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsDelegationIdRoute = SkillsDelegationIdRouteImport.update({
  id: '/skills/$delegationId',
  path: '/skills/$delegationId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsSessionKeyIndexRoute =
  ConversationsSessionKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConversationsSessionKeyRoute,
  } as any)
const PhoneCallIdIndexRoute = PhoneCallIdIndexRouteImport.update({
  id: '/phone/$callId/',
  path: '/phone/$callId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsSessionKeyCallsCallIdRoute =
  ConversationsSessionKeyCallsCallIdRouteImport.update({
    id: '/calls/$callId',
    path: '/calls/$callId',
    getParentRoute: () => ConversationsSessionKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/conversations/$sessionKey': typeof ConversationsSessionKeyRouteWithChildren
  '/sessions/$': typeof SessionsSplatRoute
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/dreams/': typeof DreamsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/phone/': typeof PhoneIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/conversations/$sessionKey/': typeof ConversationsSessionKeyIndexRoute
  '/phone/$callId/': typeof PhoneCallIdIndexRoute
  '/conversations/$sessionKey/calls/$callId': typeof ConversationsSessionKeyCallsCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/sessions/$': typeof SessionsSplatRoute
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts': typeof ContactsIndexRoute
  '/conversations': typeof ConversationsIndexRoute
  '/dreams': typeof DreamsIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/persona': typeof PersonaIndexRoute
  '/phone': typeof PhoneIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/conversations/$sessionKey': typeof ConversationsSessionKeyIndexRoute
  '/phone/$callId': typeof PhoneCallIdIndexRoute
  '/conversations/$sessionKey/calls/$callId': typeof ConversationsSessionKeyCallsCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/conversations/$sessionKey': typeof ConversationsSessionKeyRouteWithChildren
  '/sessions/$': typeof SessionsSplatRoute
  '/skills/$delegationId': typeof SkillsDelegationIdRoute
  '/contacts/': typeof ContactsIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/dreams/': typeof DreamsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/phone/': typeof PhoneIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/conversations/$sessionKey/': typeof ConversationsSessionKeyIndexRoute
  '/phone/$callId/': typeof PhoneCallIdIndexRoute
  '/conversations/$sessionKey/calls/$callId': typeof ConversationsSessionKeyCallsCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/sessions'
    | '/contacts/$contactId'
    | '/conversations/$sessionKey'
    | '/sessions/$'
    | '/skills/$delegationId'
    | '/contacts/'
    | '/conversations/'
    | '/dreams/'
    | '/memory/'
    | '/persona/'
    | '/phone/'
    | '/skills/'
    | '/workspace/'
    | '/conversations/$sessionKey/'
    | '/phone/$callId/'
    | '/conversations/$sessionKey/calls/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals'
    | '/sessions'
    | '/contacts/$contactId'
    | '/sessions/$'
    | '/skills/$delegationId'
    | '/contacts'
    | '/conversations'
    | '/dreams'
    | '/memory'
    | '/persona'
    | '/phone'
    | '/skills'
    | '/workspace'
    | '/conversations/$sessionKey'
    | '/phone/$callId'
    | '/conversations/$sessionKey/calls/$callId'
  id:
    | '__root__'
    | '/'
    | '/goals'
    | '/sessions'
    | '/contacts/$contactId'
    | '/conversations/$sessionKey'
    | '/sessions/$'
    | '/skills/$delegationId'
    | '/contacts/'
    | '/conversations/'
    | '/dreams/'
    | '/memory/'
    | '/persona/'
    | '/phone/'
    | '/skills/'
    | '/workspace/'
    | '/conversations/$sessionKey/'
    | '/phone/$callId/'
    | '/conversations/$sessionKey/calls/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRoute: typeof GoalsRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ConversationsSessionKeyRoute: typeof ConversationsSessionKeyRouteWithChildren
  SkillsDelegationIdRoute: typeof SkillsDelegationIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
  DreamsIndexRoute: typeof DreamsIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  PersonaIndexRoute: typeof PersonaIndexRoute
  PhoneIndexRoute: typeof PhoneIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  PhoneCallIdIndexRoute: typeof PhoneCallIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$sessionKey': {
      id: '/conversations/$sessionKey'
      path: '/conversations/$sessionKey'
      fullPath: '/conversations/$sessionKey'
      preLoaderRoute: typeof ConversationsSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreams/': {
      id: '/dreams/'
      path: '/dreams'
      fullPath: '/dreams/'
      preLoaderRoute: typeof DreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/': {
      id: '/persona/'
      path: '/persona'
      fullPath: '/persona/'
      preLoaderRoute: typeof PersonaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/': {
      id: '/phone/'
      path: '/phone'
      fullPath: '/phone/'
      preLoaderRoute: typeof PhoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$': {
      id: '/sessions/$'
      path: '/$'
      fullPath: '/sessions/$'
      preLoaderRoute: typeof SessionsSplatRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$delegationId': {
      id: '/skills/$delegationId'
      path: '/skills/$delegationId'
      fullPath: '/skills/$delegationId'
      preLoaderRoute: typeof SkillsDelegationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$sessionKey/': {
      id: '/conversations/$sessionKey/'
      path: '/'
      fullPath: '/conversations/$sessionKey/'
      preLoaderRoute: typeof ConversationsSessionKeyIndexRouteImport
      parentRoute: typeof ConversationsSessionKeyRoute
    }
    '/phone/$callId/': {
      id: '/phone/$callId/'
      path: '/phone/$callId'
      fullPath: '/phone/$callId/'
      preLoaderRoute: typeof PhoneCallIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$sessionKey/calls/$callId': {
      id: '/conversations/$sessionKey/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/conversations/$sessionKey/calls/$callId'
      preLoaderRoute: typeof ConversationsSessionKeyCallsCallIdRouteImport
      parentRoute: typeof ConversationsSessionKeyRoute
    }
  }
}

interface SessionsRouteChildren {
  SessionsSplatRoute: typeof SessionsSplatRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSplatRoute: SessionsSplatRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface ConversationsSessionKeyRouteChildren {
  ConversationsSessionKeyIndexRoute: typeof ConversationsSessionKeyIndexRoute
  ConversationsSessionKeyCallsCallIdRoute: typeof ConversationsSessionKeyCallsCallIdRoute
}

const ConversationsSessionKeyRouteChildren: ConversationsSessionKeyRouteChildren =
  {
    ConversationsSessionKeyIndexRoute: ConversationsSessionKeyIndexRoute,
    ConversationsSessionKeyCallsCallIdRoute:
      ConversationsSessionKeyCallsCallIdRoute,
  }

const ConversationsSessionKeyRouteWithChildren =
  ConversationsSessionKeyRoute._addFileChildren(
    ConversationsSessionKeyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRoute: GoalsRoute,
  SessionsRoute: SessionsRouteWithChildren,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ConversationsSessionKeyRoute: ConversationsSessionKeyRouteWithChildren,
  SkillsDelegationIdRoute: SkillsDelegationIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
  DreamsIndexRoute: DreamsIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  PersonaIndexRoute: PersonaIndexRoute,
  PhoneIndexRoute: PhoneIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  PhoneCallIdIndexRoute: PhoneCallIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
